name: Deploy PhotoFetchr

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to deployment directory
        run: |
          rsync -a --delete ./ /opt/stacks/hass/photofetchr
          cd /opt/stacks/hass/photofetchr
          docker compose up -d --build photofetchr
