name: Deploy PhotoFetchr

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          printf "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config

      - name: Deploy to Raspberry Pi
        run: |
          ssh -i ~/.ssh/id_rsa pi@${{ secrets.PI_HOST }} \
            "cd /opt/stacks/hass && git pull && docker compose up -d --build photofetchr"
